### ISSUE TITLE
Cannot select text

### ISSUE THREAD

**Issue by r-j-davis** [theKashey/vue-focus-lock#12]
You cannot select text inside of the trap to copy/paste.

**Comment by theKashey** [comment]
Oh, known issue. Was already fixed in another versions of lock, but not for a `vue` one.

**Comment by r-j-davis** [comment]
Thanks @theKashey, any idea on the ETA of this?

**Comment by theKashey** [comment]
It's actually shall already work, the code it there

**Comment by theKashey** [comment]
Yep, was fixed in 1.3.0, working in the current master(`yarn storybook`) - 100%

**Comment by r-j-davis** [comment]
Ah sorry, I was using 1.2. It's working now :)

**Comment by theKashey** [comment]
:)
