### ISSUE TITLE
TypeError when running test suite

### ISSUE THREAD

**Issue by deifyed** [theKashey/vue-focus-lock#14]
Hey!

I've recently added vue-focus-lock to my project, and I really like it. Works like a charm with minimal to no config out of the box. Great job!

However in testing with vue-test-utils, I'm getting

> TypeError: Cannot read property 'activeElement' of null

    at Immediate.activateTrap (/Users/deifyed/origo/developer-portal-frontend/source/node_modules/vue-focus-lock/dist/index.js:696:34)
    at processImmediate (timers.js:632:19)
on all pages that contains the modal where I'm using this plugin. Am I doing something wrong, or is this a bug?

Adding the following to line 696 seems to fix my problem, however I don't know the code well enough to know if this causes any other problems.
`      if (document)
        lastActiveFocus = document.activeElement;`

**Comment by theKashey** [comment]
Yep, document might not exists in the testing environment. Internal logic should _early return_ in such cases.

**Comment by deifyed** [comment]
Is this something you'd care to fix? Or must I become one with the code and conjure up a satisfactory PR? : P

**Comment by theKashey** [comment]
It's more about - only you can test it properly.
Basically only one change is required - `lastActiveFocus = document && document.activeElement;`, and we just have to double check that that would be enough.

You may change this line directly in your `node_modules`, and once you'll – "👍", I'll – "🚀". Deal 😉?

**Comment by deifyed** [comment]
`lastActiveFocus = document && document.activeElement;` 👍

😉!

(Thanks for the quick fixage and a smile or two)

**Comment by theKashey** [comment]
Ok, releasing a new version in 30 minutes...

**Comment by deifyed** [comment]
I'm getting a related 
`TypeError: Cannot read property 'activeElement' of null
    at data.onActivation (/source/node_modules/vue-focus-lock/dist/index.js:796:79)
    at Immediate.activateTrap (/source/node_modules/vue-focus-lock/dist/index.js:694:9)
    at processImmediate (timers.js:632:19)`
However, I'm able to just stub focus-lock in this case, so it doesn't bother me. Let me know if you want me to test out a potential fix, if you feel like doing anything here
