### ISSUE TITLE
no-focus-guards="tail" throws error

### ISSUE THREAD

**Issue by juliandreas** [theKashey/vue-focus-lock#17]
I am trying to use the no-focus-guards with no success.

```
<FocusLock no-focus-guards="tail">
   <div></div>
</FocusLock>
```

`[Vue warn]: Invalid prop: type check failed for prop "noFocusGuards". Expected Boolean, got String with value "tail".`

So it expects a true or false, not a string. Can this be fixed?

**Comment by theKashey** [comment]
👍

**Comment by theKashey** [comment]
Was fixed in https://github.com/theKashey/vue-focus-lock/pull/15
