### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by 746ideas** [theKashey/vue-focus-lock#22]
Will you support vue 3? You need only few changes to support it

**Comment by theKashey** [comment]
Sorry, really non-vue user and not sure what is missing to support version 3.
Help needed

**Comment by 746ideas** [comment]
@theKashey just rename hook destroyed() to beforeUnmount() and update dependencies to be compatible with vue 3

**Comment by theKashey** [comment]
would it break vue<3 support?

**Comment by 746ideas** [comment]
Yes, it will. You should make new release only for vue 3

**Comment by nikomax** [comment]
It doesn't work for me.
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/19823626/198984663-5ca3e6bd-9092-4d56-b9e5-a6a8777e6382.png">
