### ISSUE TITLE
[Regression] errors using vue-focus-lock 2.0.X with Vue 2.7

### ISSUE THREAD

**Issue by tbl0605** [theKashey/vue-focus-lock#25]
Hi,
when using Vue.js 2 and vue-focus-lock 2.0.0 I get now following warnings in the navigator console:
`[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().`
`[Vue warn]: onDestroyed is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().`

The firefox debugger points me to following compiled code:
```
(0, _vueDemi.onMounted)(function () {
      data.value.vue = (0, _vueDemi.getCurrentInstance)();
      data.value.observed = rootEl.value.querySelector("[data-lock]");
...
```

```
(0, _vueDemi.onUnmounted)(function () {
      instances = instances.filter(function (_ref3) {
        var vue = _ref3.vue;
        return vue !== (0, _vueDemi.getCurrentInstance)();
      });
...
```

which are the onMounted/onUnmounted methods from vue-focus-lock.

Reverting to version v1.4.1 solves the problem with Vue.js 2

Thierry.

**Comment by theKashey** [comment]
> introduced in https://github.com/theKashey/vue-focus-lock/pull/24 in order to _support_ Vue2 and 3.

I am not a Vue developer, calling @emuvente 🙏 for help

**Comment by emuvente** [comment]
I think this is caused by the build/publish process for this package that compiles the dependencies into dist/index.js along with the lock component. Specifically, that means that the `currentInstance` variable in the `@vue/composition-api` module is duplicated between the compiled version of this package and the module in the dependencies for projects that use vue-focus-lock. That `currentInstance` variable needs to be defined for the warning to not occur, but only one of the two duplicates is ever defined and it's not the one that is being checked by that warning.

It also looks like doing that compilation means that it won't work with vue3 either, because the vue-demi library gets configured for vue2 at compile time.

I did not encounter this issue in my own projects because I use the Lock.vue component directly from the `src/` directory instead of using the compiled main index.js.

@theKashey I'm not sure what the best way to resolve this would be, as I do not have much experience with package publishing. Maybe the `vue-demi` and `@vue/composition-api` modules need to be defined as externals in the webpack config so that they aren't included in the final bundle?

**Comment by tbl0605** [comment]
I hope you'll find a solution.
If you want me to test some code, feel free to create a test branch, I'll test it on my projects with pleasure.

**Comment by emuvente** [comment]
@tbl0605 I think #27 should resolve this issue. Could you try the fix out and see if the warnings clear up?

**Comment by theKashey** [comment]
Fix released as v`2.0.2`

**Comment by tbl0605** [comment]
Hi @theKashey,
sadly it doesn't work for me!

I first had this problem after upgrading:
```
This dependency was not found:
* @vue/composition-api/dist/vue-composition-api.mjs in ./node_modules/vue-focus-lock/node_modules/vue-demi/lib/index.mjs
```

I fixed it by doing:
```
npm install @vue/composition-api
```

After that my project compiled but now I have following runtime errors:
```
errorHandler TypeError: vm._watchers is undefined
    createWatcher vue-composition-api.mjs:1395
    watch vue-composition-api.mjs:1442
    setup index.js:489
    mergedSetupFn vue-composition-api.mjs:2165
    VueJS 28
    js main.js:65
    Webpack 7
        __webpack_require__
        fn
        1
        __webpack_require__
        checkDeferredModules
        <anonymous>
        <anonymous>
```

I'm using Vue 2.7.14

**Comment by theKashey** [comment]
🫠 oh no

**Comment by tbl0605** [comment]
I reproduced the problem using `vue create vue-imask-bug` and a minimalistic package.json:

```
{
  "name": "vue-imask-bug",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@vue/composition-api": "^1.7.1",
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-custom-element": "*",
    "vue-focus-lock": "*",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.19",
    "@vue/cli-plugin-eslint": "~4.5.19",
    "@vue/cli-plugin-router": "~4.5.19",
    "@vue/cli-plugin-vuex": "~4.5.19",
    "@vue/cli-service": "~4.5.19",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "compression-webpack-plugin": "<7.0.0",
    "duplicate-package-checker-webpack-plugin": "*",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^6.2.2",
    "inspectpack": "*",
    "prettier": "^2.7.1",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11",
    "webpack-bundle-analyzer": "^4.8.0"
  }
}
```

App.vue:
```
<template>
  <div id="app">
    <FocusLock>
      <div id="nav">
        <router-link to="/">Home</router-link> |
        <router-link to="/about">About</router-link>
      </div>
      <router-view />
    </FocusLock>
  </div>
</template>

<script>
import Trap from 'vue-focus-lock';

export default {
  components: { FocusLock: Trap }
};
</script>

<style lang="scss">
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
#nav {
  padding: 30px;
  a {
    font-weight: bold;
    color: #2c3e50;
    &.router-link-exact-active {
      color: #42b983;
    }
  }
}
</style>
```

**Comment by tbl0605** [comment]
Btw, with actual package.json, only the (very old) version 0.5.4 of focus-lock will be retrieved:

https://github.com/theKashey/vue-focus-lock/blob/0c9959967a5a94cae872538d357f12b15742dd41/package.json#L66

You can try the semantic version "^0.5.4" here : https://semver.npmjs.com/

**Comment by theKashey** [comment]
Look like `vue-demi`, the library used to handle Vue2 and 3 requires `@vue/composition-api` for Vue 2.
It is marked as peer dependency of this library as well. So you are "expected" to have it, but this expectation is not very clearly articulated. Hopefully, build step doing that.

However why watchers are undefined, or what it is - no idea. I would not except vue-own package to do something wrong.
In any way I am unfortunately not a vue expert to help here.

**Comment by theKashey** [comment]
Look like `vue-demi` as well as `composition-api` is no longer working with `vue@2.7`

> With the release of [Vue 2.7](https://blog.vuejs.org/posts/vue-2-7-naruto.html), which has Composition API built-in, you no longer need this plugin. Thereby this plugin has entered maintenance mode and will only support Vue 2.6 or earlier. This project will reach End of Life by the end of 2022.

There are 2 options:
- you can use `vue<2.7` or `vue>3.0`
- someone can patch vue-demi to handle `vue>2.6`

**Comment by tbl0605** [comment]
> Look like `vue-demi` as well as `composition-api` is no longer working with `vue@2.7`

Ok, so Vue 2.7 should then be handled apart, thank you for pointing to the real problem.

> 
> There are 2 options:
> 
>     * you can use `vue<2.7` or `vue>3.0`
> 
>     * someone can patch vue-demi to handle `vue>2.6`

Meanwhile, I will try a third option, directly import focus-lock and copy+adapt Lock.vue for my use. Maybe I will find an easy fix and backport it to the official vue-focus-lock repository ;)

**Comment by tbl0605** [comment]
I found a workaround to this problem:

- create a project using `vue create vue-imask-bug`
- use following package.json (npm-force-resolutions works with npm < 7.0.0, replace "resolutions' with "overrides" for more recent npm versions):
```
{
  "name": "vue-imask-bug",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "preinstall": "npx force-resolutions"
  },
  "resolutions": {
    "focus-lock": "0.*",
    "vue-demi": "^0.13.11"
  },
  "dependencies": {
    "@vue/composition-api": "^1.7.1",
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-custom-element": "*",
    "vue-focus-lock": "*",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.19",
    "@vue/cli-plugin-eslint": "~4.5.19",
    "@vue/cli-plugin-router": "~4.5.19",
    "@vue/cli-plugin-vuex": "~4.5.19",
    "@vue/cli-service": "~4.5.19",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "compression-webpack-plugin": "<7.0.0",
    "duplicate-package-checker-webpack-plugin": "*",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^6.2.2",
    "inspectpack": "*",
    "npm-force-resolutions": "*",
    "prettier": "^2.7.1",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11",
    "webpack-bundle-analyzer": "^4.8.0"
  }
}
```
- use following App.vue:
```
<template>
  <div id="app">
    <FocusLock>
      <div id="nav">
        <router-link to="/">Home</router-link> |
        <router-link to="/about">About</router-link>
      </div>
      <router-view />
    </FocusLock>
  </div>
</template>

<script>
import Trap from 'vue-focus-lock';

export default {
  components: { FocusLock: Trap }
};
</script>

<style lang="scss">
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
#nav {
  padding: 30px;
  a {
    font-weight: bold;
    color: #2c3e50;
    &.router-link-exact-active {
      color: #42b983;
    }
  }
}
</style>
```

So replacing in vue-focus-lock's package.json:
```
  "dependencies": {
    "focus-lock": "^0.5.4",
    "vue-demi": "^0.12.1"
  }
```
by
```
  "dependencies": {
    "focus-lock": "0.*",
    "vue-demi": "^0.13.11"
  }
```
should solve this bug.

**Comment by tbl0605** [comment]
Sorry for my previous comment,
actually it did just work for my "vue-imask-bug" demo project, but in more complex projects I still have the "errorHandler TypeError: vm._watchers is undefined" errors.

So for now, as long as I stick with Vue 2.7 I'll do following workaround:
- `npm install focus-lock` 
- copy https://github.com/theKashey/vue-focus-lock/blob/master/src/Lock.vue in my Vue projects
- replace in my local Lock.vue
https://github.com/theKashey/vue-focus-lock/blob/0c9959967a5a94cae872538d357f12b15742dd41/src/Lock.vue#L14
by
```
import { computed, getCurrentInstance, onMounted, onUnmounted, ref, toRefs, watch } from 'vue'; 
```

Not a great solution, but it works.

**Comment by theKashey** [comment]
The last version `2.0.3` supposed to work without issues.

The root cause is `0.*` version of `vue-demi` altering semantic version behavior and _locking_ you in an older version of vue-demi not supporting 2.7

Updating vue-demi (and composition-api, kudos to #28) solves the problem

**Comment by tbl0605** [comment]
Hi @theKashey,
thank you very much for solving this issue :) I can now use the latest version of vue-focus-lock with Vue 2.7!

I now have another regression, but that's maybe in my code, I'll have a look before opening another bug report.
