### ISSUE TITLE
[Accessibility] Tabindex should never be >0

### ISSUE THREAD

**Issue by whimsicallyson** [theKashey/vue-focus-lock#26]
https://github.com/theKashey/vue-focus-lock/blob/master/src/Lock.vue#L4 has a tabindex of 1 when focus guards are active (by default). WCAG states that tabindex > 0 should never be used, see this [explanation](https://webaim.org/techniques/keyboard/tabindex)

**Comment by theKashey** [comment]
Linking a similar issue from sibling solution - https://github.com/theKashey/react-focus-lock/issues/32

**Comment by theKashey** [comment]
fixed in v2.0.1
