### ISSUE TITLE
Error while installing on nuxt3/vue3 project

### ISSUE THREAD

**Issue by ltoussaint** [theKashey/vue-focus-lock#28]
I have a brand new project using Vue3.
When I want to install this library, I have the error below.

```
npm install --save vue-focus-lock@
2.0.2
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: nuxt3-digital-lv-front@undefined
npm ERR! Found: vue@3.2.47
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.2.45" from @nuxt/test-utils@3.0.0
npm ERR!   node_modules/@nuxt/test-utils
npm ERR!     dev @nuxt/test-utils@"3.0.0" from the root project
npm ERR!   peer vue@"^3.2.45" from @nuxt/vite-builder@3.0.0
npm ERR!   node_modules/@nuxt/vite-builder
npm ERR!     dev @nuxt/vite-builder@"3.0.0" from the root project
npm ERR!   15 more (vue-demi, vue-i18n-routing, @unhead/vue, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! vue-focus-lock@"2.0.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.0.0-rc.1" from vue-focus-lock@2.0.2
npm ERR!     node_modules/vue-focus-lock
npm ERR!       vue-focus-lock@"2.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/toussaila/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/toussaila/.npm/_logs/2023-02-20T11_29_49_634Z-debug.log
```

I think we should remove `@vue/composition-api` for the dependencies and keep it in peerDependencies.
We should give users the possibility to choose between having the composition-api or Vue3.

**Comment by theKashey** [comment]
According to #33 it still does not work with Vue 3 and I was able to replicate exactly the same problem via a totally fresh Vue3 example.
Wondering if you might know the secret

**Comment by ltoussaint** [comment]
I'll check if I see something on my side

**Comment by surgiie** [comment]
Any update on this?

**Comment by ltoussaint** [comment]
The component itself works just fine but the difficulty is to have a single build working with vue <= 2.6 in addition to vue 2.7 and vue 3.

I think the easiest solution is to create a new major version which will only support vue3 and replace webpack with vite.

User working with vue <=2.7 will have to download vue-focus-lock ^2.0.5
User working with vue >=3 will have to download vue-focus-lock ^3.0.0

@theKashey what do you think?

**Comment by tbl0605** [comment]
Hi everybody,
@theKashey, could we have a version 3 of vue-focus-lock that will work with Vue 3.x please ?

**Comment by theKashey** [comment]
Hey, not a Vue developer, so no idea what should be done. 

Help would be more than appreciated 🙏
