### ISSUE TITLE
[Regression] property "disable" doesn't work anymore using vue-focus-lock 2.0.3 and Vue 2.7

### ISSUE THREAD

**Issue by tbl0605** [theKashey/vue-focus-lock#31]
Hi,
now that issue #25 is fixed, I encounter another regression using vue-focus-lock 2.0.3 and Vue 2.7

In one of my projet, I have sometimes to disable and re-enable the focus lock by doing `<Lock :disabled="disableAppFocusLock">`.
The disabling seems to work but not the re-enabling of the focus lock.

Following links pointed my to a solution:
[Calling useVuelidate from async setup function](https://github.com/vuelidate/vuelidate/blob/next/packages/docs/src/advanced_usage.md#calling-usevuelidate-from-async-setup-function)
[fix #1079 - Add support for Vue 2.7](https://github.com/vuelidate/vuelidate/pull/1082)

**Comment by theKashey** [comment]
Fixed in 2.0.4
