### ISSUE TITLE
property "disable" doesn't work using vue-focus-lock 2.0.4 (bug introduced by commit 0da44b0)

### ISSUE THREAD

**Issue by tbl0605** [theKashey/vue-focus-lock#34]
Hi @theKashey,
after merging my pull request #32, you reworked it and introduced a bug in commit [0da44b0](https://github.com/theKashey/vue-focus-lock/commit/0da44b0917fb53e259d5909114293942678c802d)

**Comment by theKashey** [comment]
2.0.5 released 🤜

**Comment by tbl0605** [comment]
Thank you very much @theKashey it works now :)
