### ISSUE TITLE
Is it possible to "jump" from one focus-lock to another one (using vue-focus-lock)?

### ISSUE THREAD

**Issue by tbl0605** [theKashey/vue-focus-lock#36]
Hi,
first of all thank you for this great library :)

I have some complex pages where (essentially) there are two (or more) separate forms.
I would like to initially lock the focus inside the first form, unless the user clicks (using the mouse) on a field inside the second form (where I also put a focus lock).
I tried to use two "Trap" components but since they are not "connected" together, the first "Trap" component doesn't allow to "jump" inside the second one. See my [demo](https://codesandbox.io/s/vue-focus-lock-demo-6lwqcp).

Would it be possible to add an option to "escape" a focus lock as long as the user (immediately) moves the focus inside another focus lock?

Thank you!

**Comment by theKashey** [comment]
A very interesting use case, not exactly sure accessible. __Are you sure you want to do it__, as there will be no option for keyboard-only user to escape the current lock?

Long story short - vue-focus-lock will not work here and configuration may be a little hectic. However, you can implement what you want using `focus-lock` directly.

All you need is `moveFocusInside` / `attachHandler` and `dettachHandler`. The trick is to point `observed`  (https://github.com/theKashey/vue-focus-lock/blob/master/src/Lock.vue#L48) to the node you need to be a "focus boundary".

It's pretty ease to build what you want _locally_, but very hard to implement as a generic solution. Feel free to copy-paste vue-focus-lock and make corresponding changes

**Comment by tbl0605** [comment]
Hi @theKashey,
thank you very much for your reply and for pointing me in the right direction.

I will see what solution to choose, maybe I won't use focus-lock for this use case, but just catch tab events on first and last input (through `@keydown.tab.exact.prevent` and `@keydown.shift.tab.exact.prevent`) to switch between forms when using the keyboard.
In any case, it will be something specific to these forms.

Thank you!

**Comment by theKashey** [comment]
All depends on how you want this to work. Good luck
