### ISSUE TITLE
Submit action by press enter when focus on the field

### ISSUE THREAD

**Issue by Demetri0** [theKashey/vue-focus-lock#6]
When I making the form i would like for user can submit form by click enter in the last field, but using this component avoid this native behavior.
How can I implement this one? And probably you need to provide more details in the readme for describe it for the future.

**Comment by theKashey** [comment]
Sorry. Didn't get the point. 
Focus lock is working only with `focus` behaviour and should not prevent anything else.

**Comment by Demetri0** [comment]
Oh, sorry... I was just my mistake. Doesn't meter, thank you again :)
