### ISSUE TITLE
Specify the first field which will get the focus

### ISSUE THREAD

**Issue by Demetri0** [theKashey/vue-focus-lock#7]
When I making modals, I would like to place close button in the top of modal, but then close button will get focus as the first element, I would like to skip one or more fields or specify first field directly.
Could you please let me know how to do it and maybe extend your readme with this information.

Now if I set `tabindex` to the first field in the modal - I will have to specify it for all fields... maybe it is OK, but... probably you have any idea how to make it better.
btw, this solution isn't work, because it mess the tabulation order... first time it will work as expected `(1, 2, 3, [close(w/o tabindex)])`, but in the second loop it will `1, 2, 1, [close(w/o tabindex)], 3`

**Comment by theKashey** [comment]
Tab index is not something you should ever use, especially for this case.
You need __autoFocus__.

Sorry, I am not giving enough attention to Vue port, as long I don't know Vue well :) As a result it misses some features, which are actually supported by underlaying library.

see: https://github.com/theKashey/react-focus-lock/blob/master/src/AutoFocusInside.js, or, better https://github.com/theKashey/react-focus-lock#autofocus

All you need to do:
```js
<div data-autofocus-inside> // <-- this data attrubite indicate focus should be moved to the first "focusable" inside this node
    {children}
</div>

<button data-autofocus/> // <-- focus should be moved here
```

I should update readme 🤷‍♂️

**Comment by Demetri0** [comment]
Damn! it was too easy, I really forget about `autofocus`. Thank you :)
