### ISSUE TITLE
Why lock select?

### ISSUE THREAD

**Issue by romikzo** [theKashey/vue-focus-lock#9]
When i use focus-lock i can't select any text. You can see this on Demo too.

**Comment by romikzo** [comment]
Select completely not working in Chrome and Safari, in Firefox lock works very strange. Sometimes i can't unselect text.

**Comment by theKashey** [comment]
Version 1.3.0 was just released.
- 2 kb smaller
- with "unlocked" text selection

PS: I don't have any real Vue project, so all my tests are storybook-based. Could one of you verify the update?

**Comment by equinusocio** [comment]
I tried on Codesandbox:
https://codesandbox.io/s/qq3kqn6vrw

Just a question, as you can see, if i put some inputs outside the "trap" i cant focus them even if I click on them. Is this the right behaviour?

**Comment by theKashey** [comment]
That’s why it’s a focus __lock__.
See https://hackernoon.com/its-a-focus-trap-699a04d66fb5

**Comment by equinusocio** [comment]
@theKashey I have a new issue. If I add the lock in two different vue components, only one works.

**Comment by equinusocio** [comment]
@theKashey This issue is fixed on Firefox. On Chrome and Safari i can't select elements inside a locked area.

I have a modal component with the `<Lock>` and i set the `disabled` attribute when the modal is closed and i remove the attribute when it open. The selection works only on Firefox.

**Comment by equinusocio** [comment]
@theKashey I have a strange issue:

This modal content is not focusable (initially the modal content and `Lock` are empty on mount)
<img width="912" alt="schermata 2018-11-14 alle 15 49 48" src="https://user-images.githubusercontent.com/10454741/48490150-10515600-e825-11e8-8cda-2f85d18a585e.png">

This is focusable (content is present on mount)
<img width="985" alt="schermata 2018-11-14 alle 15 50 19" src="https://user-images.githubusercontent.com/10454741/48490200-30811500-e825-11e8-8333-caf41dd1a329.png">

**Comment by theKashey** [comment]
Lock and loaded :)

**Comment by equinusocio** [comment]
@theKashey I think we can close this. I don't have this issue
